#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as a wrapper:
#           ksh gradlew
#       or
#           bash gradlew
#
#   (2) This script attempts to find the Gradle home directory. If the
#       GRADLE_USER_HOME environment variable is not set, Gradle uses the
#       Gradle user home directory as defined by the Gradle manual. The
#       home directory is by default '.gradle' in the user's home directory,
#       and this script uses that as the Gradle user home directory as well.
#
#       If you have a user home directory that is not the same as the
#       user running this script (e.g., a CI server), you may want to
#       set the GRADLE_USER_HOME environment variable explicitly.
#
#   (3) The Java command to run Java will be found by searching the PATH
#       environment variable. If Java is not found, we use the JAVA_HOME
#       environment variable if it is set.
#
#   (4) The Gradle wrapper script caches the downloaded Gradle distribution
#       in the GRADLE_USER_HOME directory. The distribution is validated by
#       a SHA-256 hash. If you want to disable the cache, you may do so by
#       giving the '--no-daemon' flag or using other options listed in the
#       "Command Line Options" section of the Gradle manual.
#
#       The distribution is downloaded from Maven Central by default. You can
#       specify a different distribution by setting the distributionUrl
#       property in the 'gradle-wrapper.properties' file. By default,
#       the Gradle wrapper uses a distribution from Maven Central because
#       that's the most reliable and works for most users. If you want to
#       use a different distribution, note that it is encouraged to use a
#       distribution mirror that is verified to work.
#
#       The distribution validation uses the SHA-256 hash of the distribution
#       zip archive. It is recommended to use Gradle's built-in validation
#       (via the '--status' command line option) to verify the integrity of
#       the distribution before running any tasks.
#
#       The download and validation script can be configured by adding a
#       'gradle/wrapper/gradle-wrapper.properties' file with specific
#       properties. The 'wrapper' task in Gradle generates this properties
#       file for you. If you wish to configure any properties, you can specify
#       them in a 'gradle-wrapper.properties' file and commit it to your
#       repository along with the rest of the wrapper scripts.
#
#   (5) For tooling developers, if you want to use the 'GRADLE_USER_HOME'
#       directory to store Gradle distributions, but your CI server's
#       user home directory is not writable, you can provide a custom
#       GRADLE_USER_HOME environment variable in your build script.
#
#   (6) The initialization scripts referenced by the 'init.gradle' file
#       may be stored in the distribution location or in the gradle user
#       home directory. The distribution location takes precedence over
#       the gradle user home directory. You can also specify a custom
#       location for init scripts using the '--init-script' command line
#       option.
#
#   (7) This script uses the GRADLE_EXIT_CONSOLE variable to specify that
#       the console output for the Gradle build should use the same
#       console encoding as the Gradle script. If you don't want that,
#       you can unset the GRADLE_EXIT_CONSOLE environment variable or set
#       it to 'false'.
#
#   (8) The performance of the 'assemble' task may be impacted by
#       downloading Gradle distributions if your network connection
#       is slow. To improve performance, you can configure the
#       'org.gradle.welcome' feature flag to 'disabled' in the
#       'gradle.properties' file. This will prevent the wrapper from
#       downloading a new distribution on each new build if the
#       distribution already exists.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available file descriptors if possible
if command -v ulimit > /dev/null 2>&1 ; then
    ulimit -n 4096 || true  # Ignore failure in case it's not supported
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the script class name (expected to be 'org.gradle.wrapper.GradleWrapperMain')
#   * the jar file path (the jar file is expected to be in the same directory as this script)
#   * all the positional arguments after '--'

set -- \
        org.gradle.wrapper.GradleWrapperMain \
        "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        "$@"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ "$(uname)" = "Darwin" ] && [ -x "/usr/sbin/sysctl" ] && [ "$(/usr/sbin/sysctl -n kern.maxfilesperproc 2>/dev/null || echo 4096)" -lt 65536 ]; then
    (
        /usr/sbin/sysctl -n kern.maxfilesperproc 2>/dev/null
        /usr/sbin/sysctl -n kern.maxfiles 2>/dev/null
    ) || true
    /usr/sbin/sysctl -w kern.maxfilesperproc=65536 >/dev/null 2>&1 || true
    /usr/sbin/sysctl -w kern.maxfiles=65536 >/dev/null 2>&1 || true
    ulimit -n 65536 2>/dev/null || true
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \"\$@\""

# Use a safe default locale if LC_ALL is not set
if [ -z "$LC_ALL" ]; then
    LC_ALL=C
fi

# Determine the Gradle user home directory, which must exist for the wrapper to work
if [ -n "$GRADLE_USER_HOME" ]; then
    GRADLE_USER_HOME="$GRADLE_USER_HOME"
else
    GRADLE_USER_HOME="$HOME/.gradle"
fi

mkdir -p "$GRADLE_USER_HOME" 2>/dev/null || true

# Execute the wrapper, preserving arguments and quoting special characters (like `~` or `$')
exec "$JAVACMD" "${@}"